/**
 * Cross-language compatibility tests using golden vectors generated by Python.
 *
 * These tests verify that the Node.js implementation produces byte-identical
 * results to the Python gateway for all crypto operations.
 *
 * To regenerate golden vectors:
 *   python3 server-node/scripts/generate-golden-vectors.py > server-node/test/fixtures/golden-vectors.json
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { base64Decode } from '../../src/crypto/encoding.js';
import { payloadKey, encryptPayload, decryptPayload } from '../../src/crypto/payload-crypto.js';
import { expectedSignature, canonicalRequest } from '../../src/crypto/request-signature.js';
import { extractOtpCandidates } from '../../src/crypto/otp-extraction.js';

// Load golden vectors
const vectorsPath = join(__dirname, '..', 'fixtures', 'golden-vectors.json');
const vectors = JSON.parse(readFileSync(vectorsPath, 'utf-8'));

describe('Golden Vectors - HKDF Key Derivation', () => {
  for (const vector of vectors.hkdf) {
    it(`should derive correct key for ${vector.deviceId}`, () => {
      const secret = base64Decode(vector.secretBase64);
      const expectedKey = base64Decode(vector.derivedKeyBase64);

      const derivedKey = payloadKey(secret, vector.deviceId);

      expect(derivedKey).toEqual(expectedKey);
    });
  }
});

describe('Golden Vectors - AES-256-GCM Encryption', () => {
  for (const vector of vectors.encryption) {
    it(`should decrypt correctly for ${vector.deviceId} - ${vector.plaintextEnvelope.eventType}`, () => {
      const secret = base64Decode(vector.secretBase64);
      const encrypted = vector.encryptedEnvelope;

      // Verify we can decrypt the encrypted envelope
      const decrypted = decryptPayload(encrypted, vector.deviceId, secret);

      // The decrypted payload should match the original
      expect(decrypted.payload).toEqual(vector.decryptedPayload);
    });

    it(`should produce compatible encryption for ${vector.deviceId} - ${vector.plaintextEnvelope.eventType}`, () => {
      const secret = base64Decode(vector.secretBase64);
      const plaintext = vector.plaintextEnvelope;

      // Encrypt with Node.js
      const encrypted = encryptPayload(plaintext, vector.deviceId, secret);

      // Should have schemaVersion2
      expect(encrypted.schemaVersion).toBe(2);

      // Should be decryptable
      const decrypted = decryptPayload(encrypted, vector.deviceId, secret);
      expect(decrypted.payload).toEqual(vector.decryptedPayload);
    });
  }
});

describe('Golden Vectors - HMAC-SHA256 Signatures', () => {
  for (const vector of vectors.signatures) {
    it(`should verify signature for ${vector.deviceId}`, () => {
      const secret = base64Decode(vector.secretBase64);
      const body = base64Decode(vector.bodyBase64);

      // Verify canonical request format
      const canonical = canonicalRequest(
        vector.timestampMs,
        vector.nonce,
        vector.deviceId,
        vector.idempotencyKey,
        body,
      );
      expect(canonical.toString('utf-8')).toBe(vector.canonicalRequest);

      // Verify signature computation
      const signature = expectedSignature(
        secret,
        vector.timestampMs,
        vector.nonce,
        vector.deviceId,
        vector.idempotencyKey,
        body,
      );
      expect(signature).toBe(vector.signature);
    });
  }
});

describe('Golden Vectors - OTP Extraction', () => {
  for (let i = 0; i < vectors.otp.length; i++) {
    const vector = vectors.otp[i];
    it(`should extract OTP from test case ${i + 1}: "${vector.body.substring(0, 30)}..."`, () => {
      const candidates = extractOtpCandidates(vector.body);
      expect(candidates).toEqual(vector.expected);
    });
  }
});
